; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; --- ESP32 MASTER ENVIRONMENT ---
[env:esp32_master]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =h2zero/NimBLE-Arduino @ ^1.4.1

; --- ESP-201 (ESP8266) SNIFFER ENVIRONMENT ---
[env:esp201_sniffer]
platform = espressif8266
board = esp01_1m ; Generic 1MB ESP8266
framework = arduino
monitor_speed = 115200
upload_speed = 115200